### ISSUE TITLE
Avoid content-filtering in schools (if possible)

### ISSUE THREAD

**Issue by wachunga** [canadianveggie/spellie#108]
Here in Vancouver, some schools (like my kids' elementary) can't use Spellie — it just won't load.

Likely due to content filtering that detects "game" and decides that's really bad for education.

Not sure how we get around this.

**Comment by wachunga** [comment]
A few updates:
- Some firewalls like SF Ballet allow wordlekids.com but not spelliegame.com
- Some BC schools eg Richmond, certain Vancouver private schools have no trouble accessing it in the classroom
- I've submitted Spellie to Focused Education Resources, an org that maintains evaluated K-12 resources for BC ([which are apparently approved in the district](https://www.vsb.bc.ca/District/Departments/Office_of_the_Superintendent/Administrative-Procedures-Manual/Administrative%20Procedures%20Manual%20Library/Section%20200/AP_251_zAppendix_Digital_Learing_Tools.pdf))

**Comment by canadianveggie** [comment]
Unblocked at the VSB. So success! :D
