### ISSUE TITLE
Use Overlays for Secondary Pages

### ISSUE THREAD

**Issue by canadianveggie** [canadianveggie/spellie#40]
Look into using overlays with an X instead of separate pages with a Back button.

**Comment by wachunga** [comment]
One potential downside of this approach, at least if we follow the way Wordle does it, is that the sharing button would no longer be available from the Collection page. But looking at the analytics, it seems like not too many people are sharing there anyway?

Should we follow the approach of only showing the Share button after you complete a puzzle?

**Comment by canadianveggie** [comment]
I don't think we need to do this anymore. I think me might want to add a Share button at the bottom of completed puzzles. But that can be a new issue.
