### ISSUE TITLE
Remove bad words from dictionary

### ISSUE THREAD

**Issue by canadianveggie** [canadianveggie/spellie#45]
I wouldn't go as far as what the NYT has gone, but anything on a bad words filter should probably be removed. I noticed that SHIT and CRAP were in our dictionary and should probably be removed.

https://tech.hindustantimes.com/gaming/news/taboo-new-york-times-removes-some-insensitive-words-from-wordle-71645009066531.html

**Comment by canadianveggie** [comment]
All the bad-word lists I can find also remove medical terms like PENIS and VAGINA which I don't like
https://www.npmjs.com/package/bad-words
https://www.npmjs.com/package/badwords-list

**Comment by deelan** [comment]
Do you want to have them programmatically removed at build or runtime, or just hand excised from the dictionary?

**Comment by canadianveggie** [comment]
I think a hand exercise is fine, but maybe a test case to enforce that we don't have any left.
