### ISSUE TITLE
Better icon

### ISSUE THREAD

**Issue by canadianveggie** [canadianveggie/spellie#55]
Something better than this
![android-chrome-512x512](https://user-images.githubusercontent.com/513961/154824680-23e55149-018a-44fa-9f5f-3ccb35faf52f.png)

**Comment by jamesdodds3** [comment]
![spellie](https://user-images.githubusercontent.com/13321989/154892145-982c328b-b691-4915-acac-9489384849a5.png)

What about one of the letter tiles? "S" for Spellie?

**Comment by canadianveggie** [comment]
Closed by #65
