### ISSUE TITLE
Change Sharing Text to put `spellie-` as part of the level

### ISSUE THREAD

**Issue by canadianveggie** [canadianveggie/spellie#67]
Instead of:
Spellie
easy-11: 4/6
🍀🕸️🕸️🌻
🍀🍀🕸️🍀
🍀🍀🕸️🍀
🍀🍀🍀🍀
https://spelliegame.com

I'd like to see:
spellie-easy-11: 4/6
🍀🕸️🕸️🌻
🍀🍀🕸️🍀
🍀🍀🕸️🍀
🍀🍀🍀🍀

Not sure if we should drop the url or not. Our SEO for spellie is high enough now that it seems safe.

**Comment by wachunga** [comment]
Why the hyphens at all? I don't think that's very kid-friendly.

IMO:
- the difficulty belongs at the end
- the 4/6 is obvious from the emojis already, and maybe less important to kids
- I think it's time to drop the URL - people can google it now :)

something like:

Spellie #11 (easy)
🍀🕸️🕸️🌻
🍀🍀🕸️🍀
🍀🍀🕸️🍀
🍀🍀🍀🍀

OR

Spellie #11 😎
🍀🕸️🕸️🌻
🍀🍀🕸️🍀
🍀🍀🕸️🍀
🍀🍀🍀🍀

(where difficulty is 😎 / 🤔 / 💪 or similar)

OR

Spellie #11 (easy)
🍀🕸️🕸️🌻
🍀🍀🕸️🍀
🍀🍀🕸️🍀
🍀🍀🍀🍀
unlocked: 🚪🐈

**Comment by canadianveggie** [comment]
I thought about adding the unlocked emojis in. The only risk is it can give away the puzzle solution.

I think I like the first one best. The difficulty emojis are tempting, but we need to add them to the UI first so people know that 🤔  is medium.

**Comment by wachunga** [comment]
Good point about the puzzle solution! I'm happy with #1 too.
