### ISSUE TITLE
Center Letters in Bubbles

### ISSUE THREAD

**Issue by canadianveggie** [canadianveggie/spellie#68]
They're slightly raised right now and it's bothering me.

I think it's because the circle actually extends below the div.

<img width="290" alt="Screen Shot 2022-02-21 at 2 47 53 PM" src="https://user-images.githubusercontent.com/513961/155034979-d26a5bdb-36dc-4c83-81e6-69c94da45e6d.png">

**Comment by wachunga** [comment]
Closed by https://github.com/canadianveggie/spellie/pull/72
