### ISSUE TITLE
"check your spelling"

### ISSUE THREAD

**Issue by Eilsel87** [canadianveggie/spellie#71]
I'm getting this message on a lot of my guesses. Including what my husband confirms is the correct answer. Excited to share this game with my kid if it's working!

**Comment by canadianveggie** [comment]
Thanks for the bug report. I've reverted the latest changes to asynchronously load the dictionary (#62). It's obviously causing issues.

It should be fixed within 10 minutes. Thanks for letting us know about the bug.
