### ISSUE TITLE
Fix styling for older iPhones

### ISSUE THREAD

**Issue by deelan** [canadianveggie/spellie#87]
Spotted in the wild on an iPhone 7 (safari):
![D602A32A-6AA7-4904-A2B5-5C155B05B545](https://user-images.githubusercontent.com/10489815/155899475-a8d8c8af-41a0-4e52-9c5f-3a14361957a6.jpeg)

Letter tiles are squished and hard to read.

**Comment by canadianveggie** [comment]
<img width="1759" alt="Screen Shot 2022-03-01 at 7 51 31 AM" src="https://user-images.githubusercontent.com/513961/156201906-f7624d33-31db-455c-aa0a-20216f08ded6.png">

**Comment by canadianveggie** [comment]
<img width="1157" alt="Screen Shot 2022-03-02 at 3 19 54 PM" src="https://user-images.githubusercontent.com/513961/156466213-1560fbc0-9e76-4d06-addf-f560327bc25f.png">
